### ISSUE TITLE
I can´t generate a api whit rails formation

### ISSUE THREAD

**Issue by julianog12** [pdabrowski6/rails-formation#2]
I need create a api whit rails formation

**Comment by paweld-iRonin** [comment]
@julianog12 currently only monolith application is supported but I plan to introduce the API option (with GraphQL and REST API) in the future

**Comment by pdabrowski6** [comment]
@julianog12 it's now possible to create API with formation - you can choose the architecture (monolith or API) when creating template (or updating)
